kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: student-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: student-role
subjects:
- kind: Group
  name: students  # Ensure your OIDC provider has this group
  apiGroup: rbac.authorization.k8s.io